'''
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

https://leetcode.com/problems/find-the-difference/
'''

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        store=dict()
        for i in s:
            if i in store:
                store[i]+=1
            else:
                store[i]=1
        
        for i in t:
            if i in store:
                store[i]-=1
                if(store[i]==0):
                    del store[i]
            else:
                store[i]=1
        
        #print(store)
        for key,val in store.items():
                return key
        